### PR TITLE
Fix progress display of rejudgings that apply automatically.

### LINKED ISSUE #2141: Rejudging is incorrectly displayed in overview as 0% done
I you create a rejudging where the results are applied automatically, in the overview of rejudgings it will always say 0% done. Probably we need to adjust our query to include already applied judgings in the calculation as well.

### PR DESCRIPTION
**Pull request by meisterT**
Fixes #2141.

### CODE REVIEW

File: webapp/src/Service/RejudgingService.php [hunk 1]
```diff
@@ -390,31 +390,27 @@ public function finishRejudging(Rejudging $rejudging, string $action, ?callable
...
-            ->getSingleScalarResult();
-
-        $done = $this->em->createQueryBuilder()
+        $queryBuilder = $this->em->createQueryBuilder()
             ->from(Judging::class, 'j')
             ->select('COUNT(j)')
             ->andWhere('j.rejudging = :rejudging')
+            ->setParameter('rejudging', $rejudging);
+
+        $clonedQueryBuilder = clone($queryBuilder);
```
Comment (nickygerritsen) [inline webapp/src/Service/RejudgingService.php:402]:
```suggestion
        $clonedQueryBuilder = clone $queryBuilder;
```

**Review by nickygerritsen — APPROVED** [review]
