### PR TITLE
Remove entry point detection info from compile output if successful.

### LINKED ISSUE #1822: Confusing "Info: detected entry point:" message
### Steps to reproduce
- Configure python without requiring an entry point with the default compile script.
- Submit as a team
- Click on your submission in the submission list on the team page

### Actual behaviour
image

This is confusing because it is not actionable for teams. It is leaking that we need entry points for shadowing and should not be exposed at all to teams.

### PR DESCRIPTION
**Pull request by eldering**
This only tends to confuse contestants into thinking that this is an actual error, while it is there just for informational/debug purposes. Since it is mostly useful for admins/devs only and this is already stored in the compile.meta file, filter it out.

Closes #1822

### CODE REVIEW

**Review by nickygerritsen — APPROVED** [review]

**Review by meisterT — APPROVED** [review]

**Comment by meisterT** [comment]
Integration test failure still looks related: [Nov 27 23:40:08.403] compile.sh[16716]: error: grep -v '[Dd]etected entry_point: ' failed

File: judge/compile.sh [hunk 1]
```diff
@@ -199,7 +200,16 @@ if [ ! -f compile/program ] || [ ! -x compile/program ]; then
...
 	cleanexit ${E_COMPILER_ERROR:-1}
 fi
-cat compile.tmp >>compile.out
+
+# Remove any entry point detection message when compilation succeeded,
+# since we already stored it above and it only confuses contestants.
+if ! grep -v "$ENTRY_POINT_REGEX" compile.tmp >>compile.out; then
+	 exitcode=$?
+	 # Only report real errors, not when no matches were found.
+	 if [ $exitcode -ne 1 ]; then
```
Comment (thijskh) [inline judge/compile.sh:209]: Intended was: `-gt 1`?
