### PR TITLE
Fix adding team with a user after recent validation update. Fixes #1122

### LINKED ISSUE #1122: Adding user via frontend fails
```
<html><body>
<!--StartFragment-->

This collection should contain 1 element or more. | 0 | Caused by:                                                             Symfony\Component\Validator\ConstraintViolation {#2984 ▼   root: Symfony\Component\Form\Form {#610 …}   path: "data.users[0].user_roles"   value: Doctrine\Common\Collections\ArrayCollection {#1518 …} }
-- | -- | --


<!--EndFragment-->
</body>
</html>
```

### PR DESCRIPTION
**Pull request by nickygerritsen**
Also add tests for adding teams.

### CODE REVIEW

File: webapp/src/Controller/Jury/TeamController.php [hunk 1]
```diff
@@ -429,20 +429,8 @@ public function addAction(Request $request): Response
...
-                    ->from(Role::class, 'r')
-                    ->select('r')
-                    ->andWhere('r.dj_role = :team')
-                    ->setParameter(':team', 'team')
-                    ->getQuery()
-                    ->getOneOrNullResult();
-                $user->addUserRole($role);
-                $user->setTeam($team);
-                // Also set the user's name to the team name
+                // Otherwise, set the user's name to the team name
```
Comment (mvr320) [inline webapp/src/Controller/Jury/TeamController.php:432]: Why is the user created at all? I don't think its needed for the normal add page. But thats probably not part of your PR.

**Review by mvr320 — APPROVED** [review]
As far as I can see it fixes the issue and improves on the tests.
