### PR TITLE
Catch errors when adding problems YAML.

### LINKED ISSUE #2482: Handle invalid RGB value in problemset
When importing a problemset with invalid RGB values (such as `#tobiii`), it crashes the import, and provokes an internal server error that can only be fixed by manual database changes.

### PR DESCRIPTION
**Pull request by nickygerritsen**
Fixes #2482.

### CODE REVIEW

File: webapp/src/Service/ImportExportService.php [hunk 1]
```diff
@@ -339,14 +352,35 @@ public function importProblemsData(Contest $contest, array $problems, array &$id
...
+                        $problem->getExternalid(),
+                        $error->getPropertyPath(),
+                        $error->getMessage()
+                    );
+                }
+            }
+
+            if ($hasErrors) {
+                return false;
+
```
Comment (vmcj) [inline webapp/src/Service/ImportExportService.php:372]:
```suggestion

```

File: webapp/src/Service/ImportExportService.php [hunk 2]
```diff
@@ -309,8 +309,9 @@ public function importContestData(mixed $data, ?string &$errorMessage = null, st
      *              problems?: array{name?: string, short-name?: string, id?: string, label?: string,
      *                              letter?: string, label?: string, letter?: string}} $problems
      * @param string[]|null $ids
+     * @param array<string, string[]> $messages
      */
-    public function importProblemsData(Contest $contest, array $problems, array &$ids = null): bool
+    public function importProblemsData(Contest $contest, array $problems, array &$ids = null, ?array &$messages = []): bool
```
Comment (vmcj) [inline webapp/src/Service/ImportExportService.php:314]:
```suggestion
    public function importProblemsData(Contest $contest, array $problems, array &$ids = null, ?array &$messages = []): true
```

File: webapp/src/Service/ImportExportService.php [hunk 3]
```diff
@@ -329,8 +330,20 @@ public function importProblemsData(Contest $contest, array $problems, array &$id
                 ->setTimelimit($problemData['time_limit'] ?? 10)
                 ->setExternalid($problemData['id'] ?? $problemData['short-name'] ?? $problemLabel ?? null);
 
-            $this->em->persist($problem);
-            $this->em->flush();
+            $hasErrors = false;
+            $errors    = $this->validator->validate($problem);
+            if ($errors->count()) {
+                $hasErrors = true;
```
Comment (vmcj) [inline webapp/src/Service/ImportExportService.php:336]:
```suggestion
            if ($hasErrors = $errors->count()) {
```

Not sure if we like this,

File: webapp/src/Service/ImportExportService.php (hunk 2 above)
Comment (nickygerritsen) [reply webapp/src/Service/ImportExportService.php:314]: Well no, since it doesn't return true all the time anymore now?

File: webapp/src/Service/ImportExportService.php (hunk 3 above)
Comment (nickygerritsen) [reply webapp/src/Service/ImportExportService.php:336]: I don't really like it, especially if `problem` HAS errors and contestproblem does not.

File: webapp/src/Controller/API/ProblemController.php [hunk 4]
```diff
@@ -102,9 +102,12 @@ public function addProblemsAction(Request $request): array
...
         // to import files with YAML inside them that match the JSON format
         $data = Yaml::parseFile($file->getRealPath(), Yaml::PARSE_DATETIME);
-        if ($this->importExportService->importProblemsData($contest, $data, $ids)) {
+        if ($this->importExportService->importProblemsData($contest, $data, $ids, $messages)) {
             return $ids;
         }
+        if (!empty($messages)) {
+            throw new BadRequestHttpException($this->dj->jsonEncode($messages));
+        }
         throw new BadRequestHttpException("Error while adding problems");
```
Comment (eldering) [inline webapp/src/Controller/API/ProblemController.php:111]: Wouldn't it be better to merge the contents of these exceptions into a single one? So that it is both clear where the error happens and what the underlying cause is (if any messages are there). I think this would also make the logic of the code here less weird: first conditionally throw an exception, and then finally still throw an exception.

File: webapp/src/Service/ImportExportService.php (hunk 3 above)
Comment (eldering) [reply webapp/src/Service/ImportExportService.php:336]: I'd do it like:
```
           $errors    = $this->validator->validate($problem);
           $hasErrors = $errors->count();
           if ($hasErrors) {
```
although I see that `$hasErrors` is again set further down. But then maybe from linebreaks or name make it clear that this variable has more global scope, while `$errors` is just reused.
Will leave it up to you.

File: webapp/src/Controller/API/ProblemController.php (hunk 4 above)
Comment (nickygerritsen) [reply webapp/src/Controller/API/ProblemController.php:111]: So you suggest:

```php
$message = "Error while adding problems";
if (!empty($messages)) {
	$message .= ': ' . $this->dj->jsonEncode($messages);
}
throw new BadRequestHttpException($message);
```
?

**Comment by nickygerritsen** [comment]
I somehow can't comment on your second remark, but yeah hasErrors is a more global scope. I will add a linebreak and maybe even a comment.

File: webapp/src/Service/ImportExportService.php (hunk 2 above)
Comment (vmcj) [reply webapp/src/Service/ImportExportService.php:314]: Missed that line indeed.

File: webapp/src/Controller/API/ProblemController.php (hunk 4 above)
Comment (eldering) [reply webapp/src/Controller/API/ProblemController.php:111]: Yes, that looks good to me!

**Comment by vmcj** [comment]
> I somehow can't comment on your second remark, but yeah hasErrors is a more global scope. I will add a linebreak and maybe even a comment.

You can here: https://github.com/DOMjudge/domjudge/pull/2508#discussion_r1579041421 it's a response to your response on my message. GitHub displays that in a really ugly way.

File: webapp/src/Service/ImportExportService.php (hunk 3 above)
Comment (nickygerritsen) [reply webapp/src/Service/ImportExportService.php]: I used two separate variables, what about that idea? It makes it a bit more readable.

**Review by eldering — APPROVED** [review]
LGTM
