### PR TITLE
Shadow mode related fixes

### LINKED ISSUE #2779: Shadow differences table: do not show submissions that don't have an external ID
The shadow differences table and submission list shows submissions that don't have an external ID, i.e. jury submissions we import.
We should not display those.

### LINKED ISSUE #2791: Shadowing: loading pending events does not decode event
[Here](https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Service/ExternalContestSourceService.php#L1881-L1881) we set the event on a pending warning, but it gets JSON encoded.

However, [here](https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Service/ExternalContestSourceService.php#L1881-L1881) it doesn't get unencoded, so the code crashes.

### PR DESCRIPTION
**Pull request by nickygerritsen**
Fixes #2791
Fixes #2779

### CODE REVIEW

File: webapp/src/Service/SubmissionService.php [hunk 1]
```diff
@@ -145,6 +147,8 @@ public function getSubmissionList(
             }
         }
 
+        dump($restrictions);
```
Comment (meisterT) [inline webapp/src/Service/SubmissionService.php:150]: leftover dump

**Review by meisterT — APPROVED** [review]

**Review by vmcj — APPROVED** [review]
